import Head from 'next/head'
import Image from 'next/image'
import Hero from './Hero'
import styles from '../styles/Home.module.css'


export default function Home() {

  return (
    <div className="bgimg">
    <Head>
      <title>NFT Crafter</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://raw.githubusercontent.com/JEC-Gryffindors/Python-Components/master/%5Bremoval.ai%5D_tmp-638825f6c4549.png" />
    </Head>
  <Hero />
  </div>
  );
}