import Head from 'next/head'
import Image from 'next/image'
import Hero from './Hero'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bgimg">
      <Head>
        <title>NFT Crafter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Hero />
    </div>
  )
}
